version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt install unzip -y
      - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
      - unzip terraform_0.10.4_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - ls -ltra
      - pwd
      - terraform --version
      - ./terraform init
      - ./terraform plan 
  post_build:
    commands:
      - ./terraform apply -auto-approve
