version: 0.2

eenv:
  secrets-manager:
    MY_ACCESS_KEY: myprogramatic-acccess:AWS_ACCESS_KEY
    MY_SECRET_ACCESS_KEY: myprogramatic-acccess:AWS_SECRET_ACCESS_KEY
    MY_REGION: myprogramatic-acccess:AWS_REGION


phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt install unzip -y
      - wget https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
      - unzip terraform_1.5.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - ls -ltra
      - pwd
      - terraform --version
      - terraform init 
      - echo $MY_REGION
      
      - terraform plan -var "aws_access_key=$MY_ACCESS_KEY" -var "aws_secret_key=$MY_SECRET_ACCESS_KEY" -var "aws_region=$MY_REGION"

  post_build:
    commands:
      - terraform apply -var "aws_access_key=$MY_ACCESS_KEY" -var "aws_secret_key=$MY_SECRET_ACCESS_KEY" -var "aws_region=$MY_REGION" -auto-approve 
