version: 0.2

env:
 secrets-manager:
  MY_SECRET: "AWS_ACCESS_KEY"
  MY_SECRET: "AWS_SECRET_ACCESS_KEY"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl -o terraform.zip "https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip"
      - unzip terraform.zip
      - chmod +x terraform
  build:
    commands:
      - ./terraform init
      - ./terraform plan 
  post_build:
    commands:
      - ./terraform apply -auto-approve
