version: 0.2

env:
  variables:
    access_key: "AWS_ACCESS_KEY" 
    secret_key: "AWS_SECRET_ACCESS_KEY"
    region: "AWS_REGION"
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt install unzip -y
      - wget https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
      - unzip terraform_1.5.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - ls -ltra
      - pwd
      - terraform --version
      - terraform init 

      - terraform plan -var "aws_access_key=$access_key" -var "aws_secret_key=$secret_key" -var "aws_region=$region"

  post_build:
    commands:
      - terraform apply -var "aws_access_key=$access_key" -var "aws_secret_key=$secret_key" -var "aws_region=$region" -auto-approve 
