version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl -o terraform.zip "https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip"
      - unzip terraform.zip
      - chmod +x terraform
      - mv terraform /bin
  build:
    commands:
      - ls -ltra
      - pwd
      - ./terraform init
      - ./terraform plan 
  post_build:
    commands:
      - ./terraform apply -auto-approve
